import { foldAsked } from './normalize';
import type { Dataset, DatasetTopic, Recipe } from './types';

export const DATASETS: readonly Dataset[] = [
  {
    family: 'noaa',
    seriesId: 'co2_annmean_mlo',
    sourceLabel: 'NOAA GML — Mauna Loa CO₂ annual mean',
    sourceUrl: 'https://gml.noaa.gov/ccgg/trends/data.html',
    xLabel: 'Year',
    yLabel: 'CO₂ ppm',
    topics: ['climate', 'chemistry'],
    aliases: ['mauna loa', 'keeling', 'atmospheric co2', 'atmospheric carbon dioxide', 'co2 ppm'],
  },
  {
    family: 'noaa',
    seriesId: 'ch4_annmean_gl',
    sourceLabel: 'NOAA GML — global atmospheric methane annual mean',
    sourceUrl: 'https://gml.noaa.gov/ccgg/trends_ch4/',
    xLabel: 'Year',
    yLabel: 'CH₄ ppb',
    topics: ['climate', 'chemistry'],
    aliases: ['atmospheric methane', 'methane concentration', 'ch4 ppb', 'ch₄', 'global methane'],
  },
  {
    family: 'noaa',
    seriesId: 'ozone_hole_area',
    sourceLabel: 'Our World in Data — Antarctic ozone hole (NASA Ozone Watch)',
    sourceUrl: 'https://ourworldindata.org/grapher/antarctic-ozone-hole-area',
    xLabel: 'Year',
    yLabel: 'Peak hole (million km²)',
    topics: ['climate', 'chemistry'],
    aliases: ['ozone hole', 'antarctic ozone', 'montreal protocol'],
  },
  {
    family: 'usgs',
    seriesId: 'm8_since_2000',
    sourceLabel: 'USGS earthquake catalog — magnitude 8+',
    sourceUrl: 'https://earthquake.usgs.gov/earthquakes/search/',
    xLabel: 'Place',
    yLabel: 'Magnitude',
    topics: ['geography', 'physics'],
    aliases: ['earthquake', 'earthquakes', 'quakes', 'magnitude 8'],
  },
  {
    family: 'wiki',
    seriesId: 'languages_native',
    sourceLabel: 'Wikipedia — languages by native speakers',
    sourceUrl: 'https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers',
    xLabel: 'Language',
    yLabel: 'Native speakers (millions)',
    topics: ['demography', 'geopolitics'],
    aliases: ['native speakers', 'languages by', 'mandarin'],
  },
  {
    family: 'wiki',
    seriesId: 'refugees_hosted',
    sourceLabel: 'Wikipedia — refugees by country of asylum',
    sourceUrl: 'https://en.wikipedia.org/wiki/List_of_sovereign_states_by_refugee_population',
    xLabel: 'Country',
    yLabel: 'Refugees hosted',
    topics: ['geopolitics', 'demography'],
    aliases: ['refugee', 'refugees'],
  },
  {
    family: 'wiki',
    seriesId: 'un_votes_ukraine',
    sourceLabel: 'Wikipedia — UNGA ES-11 votes on Ukraine',
    sourceUrl: 'https://en.wikipedia.org/wiki/Eleventh_emergency_special_session_of_the_United_Nations_General_Assembly',
    xLabel: 'Resolution',
    yLabel: 'Yes votes',
    topics: ['geopolitics'],
    aliases: ['un votes', 'general assembly votes', 'unga', 'votes on ukraine'],
  },
  {
    family: 'wiki',
    seriesId: 'foundry_revenue',
    sourceLabel: 'Wikipedia — semiconductor foundry revenue',
    sourceUrl: 'https://en.wikipedia.org/wiki/Foundry_model',
    xLabel: 'Foundry',
    yLabel: 'Revenue ($m)',
    topics: ['tech', 'economy'],
    aliases: ['foundry', 'tsmc', 'taiwan chips', 'advanced chips', 'semiconductor foundry'],
  },
  {
    family: 'wiki',
    seriesId: 'solar_share',
    sourceLabel: 'Wikipedia — solar power by country',
    sourceUrl: 'https://en.wikipedia.org/wiki/Solar_power_by_country',
    xLabel: 'Country',
    yLabel: 'Solar share of generation %',
    topics: ['energy', 'climate'],
    aliases: ['solar electricity', 'solar generation', 'solar share', 'solar power'],
  },
  {
    family: 'worldbank',
    seriesId: 'SP.DYN.LE00.IN',
    sourceLabel: 'World Bank — life expectancy at birth',
    sourceUrl: 'https://data.worldbank.org/indicator/SP.DYN.LE00.IN',
    xLabel: 'Country',
    yLabel: 'Years',
    topics: ['demography', 'biology'],
    aliases: ['life expectancy'],
  },
  {
    family: 'worldbank',
    seriesId: 'SP.DYN.TFRT.IN',
    sourceLabel: 'World Bank — fertility rate',
    sourceUrl: 'https://data.worldbank.org/indicator/SP.DYN.TFRT.IN',
    xLabel: 'Country',
    yLabel: 'Births per woman',
    topics: ['demography'],
    aliases: ['fertility', 'replacement', 'births per woman'],
  },
  {
    family: 'worldbank',
    seriesId: 'NY.GDP.PCAP.CD',
    sourceLabel: 'World Bank — GDP per capita',
    sourceUrl: 'https://data.worldbank.org/indicator/NY.GDP.PCAP.CD',
    xLabel: 'Country',
    yLabel: 'USD per person',
    topics: ['economy'],
    aliases: ['gdp per capita', 'gdp per person'],
  },
  {
    family: 'worldbank',
    seriesId: 'EG.ELC.ACCS.ZS',
    sourceLabel: 'World Bank — access to electricity',
    sourceUrl: 'https://data.worldbank.org/indicator/EG.ELC.ACCS.ZS',
    xLabel: 'Country',
    yLabel: 'Access %',
    topics: ['energy', 'economy'],
    aliases: ['electricity access', 'access to electricity', 'people with electricity'],
    avoid: ['solar'],
  },
  {
    family: 'worldbank',
    seriesId: 'SL.UEM.1524.ZS',
    sourceLabel: 'World Bank — youth unemployment',
    sourceUrl: 'https://data.worldbank.org/indicator/SL.UEM.1524.ZS',
    xLabel: 'Country',
    yLabel: 'Youth unemployment %',
    topics: ['economy', 'demography'],
    aliases: ['youth unemployment', 'youth jobless'],
  },
  {
    family: 'worldbank',
    seriesId: 'SP.POP.65UP.TO.ZS',
    sourceLabel: 'World Bank — population aged 65+',
    sourceUrl: 'https://data.worldbank.org/indicator/SP.POP.65UP.TO.ZS',
    xLabel: 'Country',
    yLabel: 'Share aged 65+ %',
    topics: ['demography'],
    aliases: ['aged 65', '65+', 'population aged', 'got old'],
  },
  {
    family: 'worldbank',
    seriesId: 'MS.MIL.XPND.GD.ZS',
    sourceLabel: 'World Bank — military spending (% of GDP)',
    sourceUrl: 'https://data.worldbank.org/indicator/MS.MIL.XPND.GD.ZS',
    xLabel: 'Country',
    yLabel: 'Military % of GDP',
    topics: ['geopolitics', 'economy'],
    aliases: ['military spending', 'military expenditure', 'war footing'],
  },
  {
    family: 'worldbank',
    seriesId: 'BX.TRF.PWKR.DT.GD.ZS',
    sourceLabel: 'World Bank — remittances received (% of GDP)',
    sourceUrl: 'https://data.worldbank.org/indicator/BX.TRF.PWKR.DT.GD.ZS',
    xLabel: 'Country',
    yLabel: 'Remittances % of GDP',
    topics: ['economy', 'geopolitics'],
    aliases: ['remittance', 'remittances'],
  },
  {
    family: 'worldbank',
    seriesId: 'ER.H2O.FWTL.ZS',
    sourceLabel: 'World Bank — freshwater withdrawals (% of internal resources)',
    sourceUrl: 'https://data.worldbank.org/indicator/ER.H2O.FWTL.ZS',
    xLabel: 'Country',
    yLabel: 'Withdrawals % of renewable water',
    topics: ['geography', 'ecology'],
    aliases: ['water stress', 'water-stress', 'freshwater withdrawal', 'overdrawn', 'renewable supply'],
  },
  {
    family: 'worldbank',
    seriesId: 'AG.LND.AGRI.ZS',
    sourceLabel: 'World Bank — agricultural land (% of land area)',
    sourceUrl: 'https://data.worldbank.org/indicator/AG.LND.AGRI.ZS',
    xLabel: 'Country',
    yLabel: 'Agricultural land %',
    topics: ['geography', 'ecology'],
    aliases: ['agricultural land', 'farmland', 'farm land'],
  },
  {
    family: 'fred',
    seriesId: 'UNRATE',
    sourceLabel: 'FRED — U.S. unemployment rate',
    sourceUrl: 'https://fred.stlouisfed.org/series/UNRATE',
    xLabel: 'Month',
    yLabel: 'Unemployment %',
    topics: ['economy'],
    aliases: ['us unemployment', 'u.s. unemployment', 'unrate', 'american unemployment', 'united states unemployment'],
    avoid: ['youth'],
  },
  {
    family: 'fred',
    seriesId: 'CPIAUCSL',
    sourceLabel: 'FRED — U.S. CPI',
    sourceUrl: 'https://fred.stlouisfed.org/series/CPIAUCSL',
    xLabel: 'Month',
    yLabel: 'CPI',
    topics: ['economy'],
    aliases: ['cpi', 'consumer price', 'us inflation', 'u.s. inflation', 'american inflation'],
  },
  {
    family: 'fred',
    seriesId: 'FEDFUNDS',
    sourceLabel: 'FRED — federal funds rate',
    sourceUrl: 'https://fred.stlouisfed.org/series/FEDFUNDS',
    xLabel: 'Month',
    yLabel: 'Rate %',
    topics: ['economy'],
    aliases: ['fed funds', 'federal funds rate', 'fed hiking', 'fed fund'],
  },
  {
    family: 'fred',
    seriesId: 'HOUST',
    sourceLabel: 'FRED — U.S. housing starts',
    sourceUrl: 'https://fred.stlouisfed.org/series/HOUST',
    xLabel: 'Month',
    yLabel: 'Starts (thousands)',
    topics: ['economy'],
    aliases: ['housing starts', 'housing start', 'housing permits'],
  },
  {
    family: 'owid',
    seriesId: 'temperature_anomaly',
    sourceLabel: 'Our World in Data — global temperature anomaly',
    sourceUrl: 'https://ourworldindata.org/grapher/temperature-anomaly',
    xLabel: 'Year',
    yLabel: 'Anomaly °C',
    topics: ['climate'],
    aliases: ['temperature anomaly', 'global temperature', 'global warming'],
  },
  {
    family: 'owid',
    seriesId: 'arctic_sea_ice',
    sourceLabel: 'Our World in Data — Arctic sea ice (NSIDC)',
    sourceUrl: 'https://ourworldindata.org/grapher/arctic-sea-ice',
    xLabel: 'Year',
    yLabel: 'September minimum (million km²)',
    topics: ['climate', 'ecology'],
    aliases: ['sea ice', 'arctic ice', 'arctic summer ice'],
  },
  {
    family: 'owid',
    seriesId: 'us_wildfire_area',
    sourceLabel: 'Our World in Data — area burnt by wildfires (United States)',
    sourceUrl: 'https://ourworldindata.org/grapher/annual-area-burnt-by-wildfires',
    xLabel: 'Year',
    yLabel: 'Area burned (ha)',
    topics: ['climate', 'ecology'],
    aliases: ['wildfire', 'wildfires', 'acres burned', 'fire seasons'],
  },
  {
    family: 'owid',
    seriesId: 'lithium_production',
    sourceLabel: 'Our World in Data — lithium mine production',
    sourceUrl: 'https://ourworldindata.org/grapher/lithium-production',
    xLabel: 'Country',
    yLabel: 'Production (tonnes)',
    topics: ['energy', 'economy', 'geography'],
    aliases: ['lithium'],
  },
  {
    family: 'owid',
    seriesId: 'ev_share',
    sourceLabel: 'Our World in Data — electric share of new cars',
    sourceUrl: 'https://ourworldindata.org/grapher/electric-car-sales-share',
    xLabel: 'Country',
    yLabel: 'Electric share of new cars %',
    topics: ['energy', 'tech'],
    aliases: ['electric share of new', 'electric car', 'electric cars', 'ev sales', 'new car sales'],
  },
  {
    family: 'owid',
    seriesId: 'oil_production',
    sourceLabel: 'Our World in Data — oil production',
    sourceUrl: 'https://ourworldindata.org/grapher/oil-production-by-country',
    xLabel: 'Country',
    yLabel: 'Oil production',
    topics: ['energy', 'economy'],
    aliases: ['crude oil', 'oil production', 'shale boom', 'shale'],
  },
  {
    family: 'wiki',
    seriesId: 'gold_reserves',
    sourceLabel: 'Wikipedia — official gold reserves',
    sourceUrl: 'https://en.wikipedia.org/wiki/Gold_reserve',
    xLabel: 'Country',
    yLabel: 'Gold (tonnes)',
    topics: ['economy', 'geopolitics'],
    aliases: ['gold reserves', 'gold reserve', 'official gold'],
  },
  {
    family: 'owid',
    seriesId: 'deforestation',
    sourceLabel: 'Our World in Data — annual deforestation',
    sourceUrl: 'https://ourworldindata.org/grapher/annual-deforestation',
    xLabel: 'Country',
    yLabel: 'Forest lost (ha)',
    topics: ['ecology', 'geography'],
    aliases: ['deforestation', 'deforest', 'clear-cut', 'clearcutting'],
  },
  {
    family: 'owid',
    seriesId: 'tree_cover_loss',
    sourceLabel: 'Our World in Data — tree cover loss (Global Forest Watch)',
    sourceUrl: 'https://ourworldindata.org/grapher/tree-cover-loss',
    xLabel: 'Country',
    yLabel: 'Tree cover lost',
    topics: ['ecology', 'geography'],
    aliases: ['tree cover', 'canopy'],
  },
  {
    family: 'owid',
    seriesId: 'forest_share',
    sourceLabel: 'Our World in Data — share of land covered by forest',
    sourceUrl: 'https://ourworldindata.org/grapher/forest-area-as-share-of-land-area',
    xLabel: 'Country',
    yLabel: 'Forest % of land',
    topics: ['ecology', 'geography'],
    aliases: ['forest cover', 'forested', 'forest area', 'covered by forest', 'forest country'],
    avoid: ['deforest', 'wildfire', 'tree cover'],
  },
  {
    family: 'owid',
    seriesId: 'terrestrial_protected',
    sourceLabel: 'Our World in Data — terrestrial protected areas',
    sourceUrl: 'https://ourworldindata.org/grapher/terrestrial-protected-areas',
    xLabel: 'Country',
    yLabel: 'Protected land %',
    topics: ['ecology', 'geography'],
    aliases: ['protected areas', 'protected land', 'terrestrial protected', 'habitat aside'],
    avoid: ['marine'],
  },
  {
    family: 'owid',
    seriesId: 'marine_protected',
    sourceLabel: 'Our World in Data — marine protected areas',
    sourceUrl: 'https://ourworldindata.org/grapher/marine-protected-areas',
    xLabel: 'Country',
    yLabel: 'Protected waters %',
    topics: ['ecology', 'geography'],
    aliases: ['marine protected', 'mpa', 'fishing grounds'],
  },
  {
    family: 'owid',
    seriesId: 'living_planet_index',
    sourceLabel: 'Our World in Data — Living Planet Index (WWF / ZSL)',
    sourceUrl: 'https://ourworldindata.org/grapher/living-planet-index-by-region',
    xLabel: 'Year',
    yLabel: 'Living Planet Index',
    topics: ['ecology', 'biology'],
    aliases: ['living planet', 'wildlife abundance', 'vertebrate wildlife'],
  },
  {
    family: 'owid',
    seriesId: 'fish_overexploited',
    sourceLabel: 'Our World in Data — overexploited fish stocks (FAO)',
    sourceUrl: 'https://ourworldindata.org/grapher/fish-stocks-within-sustainable-levels',
    xLabel: 'Year',
    yLabel: 'Overexploited stocks %',
    topics: ['ecology', 'biology'],
    aliases: ['fish stocks', 'fish stock', 'overfish', 'overfishing', 'overexploit'],
  },
  {
    family: 'owid',
    seriesId: 'population_density',
    sourceLabel: 'Our World in Data — population density',
    sourceUrl: 'https://ourworldindata.org/grapher/population-density',
    xLabel: 'Country',
    yLabel: 'People per km²',
    topics: ['geography', 'demography'],
    aliases: ['population density', 'densest', 'people per km', 'most crowded'],
  },
  {
    family: 'owid',
    seriesId: 'plastic_ocean',
    sourceLabel: 'Our World in Data — plastic waste emitted to the ocean',
    sourceUrl: 'https://ourworldindata.org/grapher/plastic-waste-emitted-to-the-ocean',
    xLabel: 'Country',
    yLabel: 'Plastic to ocean',
    topics: ['ecology', 'chemistry'],
    aliases: ['plastic waste', 'plastic to the ocean', 'plastic pollution', 'leaking the most'],
  },
  {
    family: 'wiki',
    seriesId: 'volcano_deaths',
    sourceLabel: 'Wikipedia — volcanic eruptions by death toll',
    sourceUrl: 'https://en.wikipedia.org/wiki/List_of_volcanic_eruptions_by_death_toll',
    xLabel: 'Volcano',
    yLabel: 'Deaths',
    topics: ['geography', 'history'],
    aliases: ['volcanic', 'volcano', 'eruptions', 'lives lost'],
  },
  {
    family: 'wiki',
    seriesId: 'wild_tigers',
    sourceLabel: 'Wikipedia — wild tiger population by country',
    sourceUrl: 'https://en.wikipedia.org/wiki/Tiger',
    xLabel: 'Country',
    yLabel: 'Wild tigers',
    topics: ['biology', 'ecology'],
    aliases: ['tiger', 'tigers', 'wild tiger', 'tiger population', 'tigers by country'],
    avoid: ['economy', 'paper'],
  },
  {
    family: 'wiki',
    seriesId: 'atlantic_hurricanes',
    sourceLabel: 'Wikipedia — Atlantic hurricane seasons',
    sourceUrl: 'https://en.wikipedia.org/wiki/List_of_Atlantic_hurricane_seasons',
    xLabel: 'Year',
    yLabel: 'Hurricanes',
    topics: ['climate', 'geography'],
    aliases: ['atlantic hurricane', 'named atlantic', 'hurricane seasons', 'named hurricanes'],
  },
  {
    family: 'owid',
    seriesId: 'world_population',
    sourceLabel: 'Our World in Data — world population',
    sourceUrl: 'https://ourworldindata.org/grapher/population',
    xLabel: 'Year',
    yLabel: 'People',
    topics: ['history', 'demography'],
    aliases: ['world population', 'human population', 'global population'],
    avoid: ['density', '65', 'urban', 'fertility', 'aged'],
  },
  {
    family: 'owid',
    seriesId: 'conflict_deaths',
    sourceLabel: 'Our World in Data — deaths in state-based conflicts (UCDP)',
    sourceUrl: 'https://ourworldindata.org/grapher/deaths-in-state-based-conflicts',
    xLabel: 'Year',
    yLabel: 'Battle deaths',
    topics: ['history', 'geopolitics'],
    aliases: ['armed conflict', 'battle deaths', 'battle death', 'conflict deaths', 'state-based'],
    avoid: ['deadliest wars', 'death toll', 'wars by death'],
  },
  {
    family: 'wiki',
    seriesId: 'wars_death_toll',
    sourceLabel: 'Wikipedia — wars by death toll',
    sourceUrl: 'https://en.wikipedia.org/wiki/List_of_wars_by_death_toll',
    xLabel: 'War',
    yLabel: 'Deaths (millions, low estimate)',
    topics: ['history', 'geopolitics'],
    aliases: ['deadliest wars', 'wars by death', 'death toll', 'world war ii'],
  },
  {
    family: 'owid',
    seriesId: 'child_mortality',
    sourceLabel: 'Our World in Data — under-five mortality',
    sourceUrl: 'https://ourworldindata.org/grapher/child-mortality',
    xLabel: 'Year',
    yLabel: 'Under-five deaths per 100 births',
    topics: ['history', 'biology', 'demography'],
    aliases: ['child mortality', 'under-five', 'under 5', 'under five', 'children dying'],
  },
  {
    family: 'owid',
    seriesId: 'extreme_poverty',
    sourceLabel: 'Our World in Data — share in extreme poverty',
    sourceUrl: 'https://ourworldindata.org/grapher/share-of-population-in-extreme-poverty',
    xLabel: 'Year',
    yLabel: 'Share in poverty %',
    topics: ['history', 'economy'],
    aliases: ['extreme poverty', 'in poverty'],
  },
  {
    family: 'owid',
    seriesId: 'literacy_rate',
    sourceLabel: 'Our World in Data — adult literacy',
    sourceUrl: 'https://ourworldindata.org/grapher/cross-country-literacy-rates',
    xLabel: 'Year',
    yLabel: 'Literacy %',
    topics: ['history', 'demography'],
    aliases: ['literacy', 'literate', 'taught the planet to read'],
  },
  {
    family: 'owid',
    seriesId: 'democracy_index',
    sourceLabel: 'Our World in Data — electoral democracy index (V-Dem)',
    sourceUrl: 'https://ourworldindata.org/grapher/electoral-democracy-index',
    xLabel: 'Year',
    yLabel: 'Electoral democracy index',
    topics: ['history', 'geopolitics'],
    aliases: ['democracy index', 'electoral democracy', 'v-dem', 'democratize'],
  },
  {
    family: 'owid',
    seriesId: 'countries_count',
    sourceLabel: 'Our World in Data — number of countries (Gleditsch and Ward)',
    sourceUrl: 'https://ourworldindata.org/grapher/number-of-countries',
    xLabel: 'Year',
    yLabel: 'Countries',
    topics: ['history', 'geopolitics'],
    aliases: ['number of countries', 'how many countries', 'decolonization'],
  },
  {
    family: 'owid',
    seriesId: 'urban_share',
    sourceLabel: 'Our World in Data — urban population share',
    sourceUrl: 'https://ourworldindata.org/grapher/share-of-population-urban',
    xLabel: 'Year',
    yLabel: 'Urban share %',
    topics: ['history', 'demography', 'geography'],
    aliases: ['urbanization', 'urbanisation', 'urban population', 'majority city'],
  },
  {
    family: 'owid',
    seriesId: 'world_gdp',
    sourceLabel: 'Our World in Data — global GDP over the long run',
    sourceUrl: 'https://ourworldindata.org/grapher/global-gdp-over-the-long-run',
    xLabel: 'Year',
    yLabel: 'World GDP',
    topics: ['history', 'economy'],
    aliases: ['world gdp', 'global gdp', 'gdp over the long', 'long-run gdp', 'long run gdp', 'hockey stick'],
    avoid: ['per capita', 'per person'],
  },
  {
    family: 'owid',
    seriesId: 'nuclear_warheads',
    sourceLabel: 'Our World in Data — deployed strategic nuclear warheads',
    sourceUrl: 'https://ourworldindata.org/grapher/nuclear-warhead-inventories',
    xLabel: 'Country',
    yLabel: 'Deployed strategic warheads',
    topics: ['physics', 'geopolitics'],
    aliases: ['warhead', 'warheads', 'nuclear arsenal', 'nuclear weapon', 'nuclear bomb'],
    avoid: ['reactor', 'reactors'],
  },
  {
    family: 'owid',
    seriesId: 'transistors',
    sourceLabel: 'Our World in Data — transistors per microprocessor',
    sourceUrl: 'https://ourworldindata.org/grapher/transistors-per-microprocessor',
    xLabel: 'Year',
    yLabel: 'Transistors',
    topics: ['physics', 'tech'],
    aliases: ['transistor', 'transistors', "moore's law", 'moores law', 'moore law'],
  },
  {
    family: 'owid',
    seriesId: 'nitrogen_fertilizer',
    sourceLabel: 'Our World in Data — nitrogen fertilizer production (FAO)',
    sourceUrl: 'https://ourworldindata.org/grapher/fertilizer-production-by-nutrient-type-npk',
    xLabel: 'Year',
    yLabel: 'Nitrogen fertilizer',
    topics: ['chemistry', 'ecology'],
    aliases: ['nitrogen fertilizer', 'haber-bosch', 'haber bosch', 'ammonia'],
  },
  {
    family: 'owid',
    seriesId: 'tuberculosis_deaths',
    sourceLabel: 'Our World in Data — tuberculosis death rate (WHO)',
    sourceUrl: 'https://ourworldindata.org/grapher/tuberculosis-death-rate',
    xLabel: 'Year',
    yLabel: 'TB deaths per 100,000',
    topics: ['biology', 'history'],
    aliases: ['tuberculosis', 'tb death', 'tb deaths', 'tb mortality'],
  },
  {
    family: 'owid',
    seriesId: 'described_species',
    sourceLabel: 'Our World in Data — number of described species',
    sourceUrl: 'https://ourworldindata.org/grapher/number-of-described-species',
    xLabel: 'Group',
    yLabel: 'Described species',
    topics: ['biology', 'ecology'],
    aliases: ['described species', 'named species', 'kinds of life', 'how many species'],
  },
];

/** @deprecated Use DATASETS. Same records; matching is retrieval, not per-row predicates. */
export const RECIPES: readonly Recipe[] = DATASETS;

export function datasetsForTopic(topic: DatasetTopic): Dataset[] {
  return DATASETS.filter((row) => row.topics.includes(topic));
}

export function rankDatasets(asked: string): Array<{ dataset: Dataset; score: number }> {
  const q = foldAsked(asked);
  const ranked: Array<{ dataset: Dataset; score: number }> = [];
  for (const dataset of DATASETS) {
    const score = scoreDataset(q, dataset);
    if (score > 0) {
      ranked.push({ dataset, score });
    }
  }
  ranked.sort((a, b) => b.score - a.score);
  return ranked;
}

export function matchPrompt(asked: string): Recipe | null {
  const text = asked.trim();
  if (text.length < 8) {
    return null;
  }
  const ranked = rankDatasets(text);
  const top = ranked[0];
  if (!top || top.score < 3) {
    return null;
  }
  const second = ranked[1];
  if (second && top.score === second.score) {
    return null;
  }
  return top.dataset;
}

function scoreDataset(asked: string, dataset: Dataset): number {
  if (dataset.avoid?.some((needle) => asked.includes(foldAsked(needle)))) {
    return 0;
  }
  let best = 0;
  let hits = 0;
  for (const alias of dataset.aliases) {
    const needle = foldAsked(alias);
    if (needle.length < 3 || !asked.includes(needle)) {
      continue;
    }
    hits += 1;
    if (needle.length > best) {
      best = needle.length;
    }
  }
  if (hits === 0) {
    return 0;
  }
  return best * 10 + hits;
}
